//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Районы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Районы()
        {
            this.Заявки = new HashSet<Заявки>();
        }
    
        public int ID_района { get; set; }
        public string Название { get; set; }
        public double Площадь { get; set; }
        public int Население { get; set; }
        public int Колличество_станций_метро { get; set; }
        public string Тип_застройки { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заявки> Заявки { get; set; }
    }
}
