//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Порты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Порты()
        {
            this.Порты_В_Оборудовании = new HashSet<Порты_В_Оборудовании>();
        }
    
        public int ID_Порта { get; set; }
        public string Тип_порта { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Порты_В_Оборудовании> Порты_В_Оборудовании { get; set; }
    }
}
